### ISSUE TITLE
%-Routine support

### ISSUE THREAD

**Issue by pisani** [intersystems/git-source-control#111]
I want to track changes to custom  %Z-routines I have installed in %SYS.   After I configured git-source-control in the %SYS namespace, added class '%ZTest.myClass.cls' then, selected 'Git - Add' exported the file to /cls/ZTest/myClass.cls - the '%' in the package name was dropped.

**Comment by isc-tleavitt** [comment]
@pisani there's a bit of a convention in source control export from InterSystems' platforms to either drop the % or replace it with _. I don't have a clear idea of why, so I'm supportive of changing the default behavior in this respect (unless immediate problems pop up). The ObjectScript package manager provides more granular control over the internal name / filesystem name conversion, and this extension will respect any behavior configured there.

**Comment by pisani** [comment]
Hi @isc-tleavitt and @isc-bspead. I figured the reason for stripping this out would be OS related.
(But in DOS, I can have filenames with % in their name). Still. perhaps the right thing to do would be to allow the utility to strip then re-apply % to _ and vice versa.  Fine-grain control over external/internal naming does not need to be implemented in the first instance imho.

**Comment by pisani** [comment]
@isc-tleavitt - re-readingn your response, perhaps the detail in my original issue description was missed.  It's not that "%" is changed to something, it's that "%" is removed altogether on export..  so package: "%ZMyTest.myclass.cls" becomes "src/cls/ZMyTest/myclass.cls" on disk (so when re-imported effectively introduces the new non-% package in the user namespace).  

I believe this is a bug, and the reason is this line in the method Name() of SourceControl.Git.Utils which says:

`  set nam=$translate(nam,"%")`

when it should say:

`  set nam=$translate(nam,"%","_")`

Do you agree ?

**Comment by isc-tleavitt** [comment]
@pisani I think this behavior should be configurable. And as I mentioned, in the package manager, it is. Supporting configurability with reasonable defaults (which would include replacing _ with %) is a good plan.

At this point it would be a backwards-incompatible change unless we jump through some crazy hoops, but I think we can allow it with a major version bump and release note.

**Comment by isc-tleavitt** [comment]
@pisani a clarifying point on your earlier comment: reimporting shouldn't introduce a new non-% package; the name of the class in the file will be respected on import rather than the filename. (Are you seeing differently?)

**Comment by pisani** [comment]
You are right @isc-tleavitt .. my bad. 
The import back into IRIS will introduce a new package.
Dont you agree however, that exports of % class should not lose the % in case users have a package name in their user namespace, that's the same as a % one (just without the leading %).  The way it stands, the exported files will overwrite each other....

**Comment by isc-tleavitt** [comment]
@pisani agreed that behavior could/should be different/better with % classes. Ideally configurable and with reasonable defaults (those being to differentiate between %PackageName and PackageName in the export location).

**Comment by isc-tleavitt** [comment]
As another example of how configurability matters: for DeepSee Folder Items we might want to have a different conversion between internal name and name on disk.

**Comment by pisani** [comment]
Yes. I agree, how the on disk export of IRIS components are named, should be configurable with a default.
