### ISSUE TITLE
Jumping from WebUI->Settings or other way doesn't respect CSP URL Web Prefix

### ISSUE THREAD

**Issue by CraigRegester** [intersystems/git-source-control#121]
Trying out the new jump from WebUI -> Settings, or the other way around, there's a bug where the CSP Web URL Prefix is not being respected here.

Figured this out using the IIS Logs that hosts Web Gateway for us. We use a URL Prefix of /ucr on this instance and it is specified in the appropriate places e.g.,

`d $System.CSP.SetConfig("CSPConfigName","ucr")`objectscript

But when attempting to use the new feature, I can see in the IIS logs it isn't being thrown in:

`2022-02-07 18:20:45 W3SVC1 GET /ucr/isc/studio/usertemplates/gitsourcecontrol/webuidriver.csp/EGMYNS/MYPKG.Productions.Edge.CLS/api/settings  <-- Here I am in WebUI settings and then I click to jump to settings...

2022-02-07 18:20:45 W3SVC1 GET /isc/studio/usertemplates/gitsourcecontrol/gitprojectsettings.csp CSPSHARE=1&NSpace=EGMYNS&Username=MYUSERID <--- note no prefix`

I had to sanitize the log a bit but happy to show visually if it helps. Biggest issue here for me is that since it goes down a different url path, I lose my session credentials and it forces me to relogin! If I access Settings or WebUI from the Source Control menu directly, both still work fine. It's just the jump back and forth when in one or the other.

**Comment by isc-tleavitt** [comment]
@isc-svelury this should be a quick fix. I think the right place to look here is actually not $System.CSP.GetConfig("CSPConfigName") but actually ^%SYS("WebServer","URLPrefix")

**Comment by isc-tleavitt** [comment]
%Studio.General:GetWebServerPort provides an API to get the prefix. (Or you could just get it from %request.Url I think? Maybe that's simpler.)
