### ISSUE TITLE
Script error on gitprojectsettings.csp

### ISSUE THREAD

**Issue by pisani** [intersystems/git-source-control#123]
Hi, - Why does my Settings page now pop up this error ?  - Seems to be related to javascript error in gitprojectsettings.csp 

![image](https://user-images.githubusercontent.com/1563535/153692483-f49f2bf3-b8e7-4af7-9dd8-41742fc2d35a.png)

Steve

**Comment by isc-svelury** [comment]
I believe this has been fixed here: https://github.com/intersystems/git-source-control/commit/96c99e02311e402b54b20dd28f1298272d5b5ad2

It shouldn't be there on main now and in future releases. In meantime, this error is only seen in Studio/IE. If you can, switching to VS Code for editing the settings would be the easiest. You could also open the URL on a web browser (other than IE) and proceed that way.

**Comment by pisani** [comment]
Hi,
Glad to see this is fixed.  Not sure what you mean re switching to VS Code for editing settings such as SSHKey, or location of GIT. More a case of modifying the ^SYS("SourceControl" global in the namespace perhaps ?    (also tried opening up the URL in a browser but got an application error) - never mind - don't need to waste more time on workarounds - I'll wait for next release.
thanks - Steve

**Comment by isc-svelury** [comment]
The extension also works on VS Code. You can access the Source Control menu either from the command palette or the source control button in the top right corner. The first option on that menu should be for the settings page. The settings page provides a UI for modifying the `^SYS("SourceControl", "Git", "settings")` global. You can also configure the settings by running
 `d ##class(SourceControl.Git.API).Configure()` in the terminal.

In any case, this issue will be resolved in the next release.
