### ISSUE TITLE
Add equivalent to $$Env^%buildccr

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/git-source-control#124]
git-source-control should have APIs similar to $$Env^%buildccr, $$IsLIVE^%buildccr (to support different stages for environments)

**Comment by isc-bspead** [comment]
@isc-tleavitt  - the logic which specifies that an environment is BASE, TEST or LIVE (or whatever environment name is to be given) should also set the global to have the SMP display dev/test/live in the banner.  It could also do the ZWELCOME changes that we do in CCR to explain the purpose of the instances.
