### ISSUE TITLE
Make it possible to uninstall while configured as the namespace's source control extension

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/git-source-control#187]
From https://github.com/intersystems/git-source-control/discussions/185:

If you try to uninstall with SourceControl.Git.Extension configured as the source control class for the namespace, the package manager tries to call in to SourceControl.Git.Extension and (of course) fails.

Solution: Uninstalling should first clear the source control class for the namespace IF it's set to SourceControl.Git.Extension. We might be able to do this via an Invoke or it might need to be a custom lifecycle class.

**Comment by isc-rsaptars** [comment]
Making sure I understand this correctly
The `SourceControlClass` should be set to `""` when uninstalling.
After the extension is reinstalled, the `SourceControlClass` is set to `SourceControl.Git.Extension` only after calling `Configure()`

**Comment by isc-tleavitt** [comment]
Correct.

**Comment by isc-rsaptars** [comment]
I have completed the task. But I was thinking and I wondered if it would make sense to reset the `SourceControlClass` to its value from before the extension was installed? If that class does not exist, then we set it to `""`.
