### ISSUE TITLE
Review "Export All" with respect to routines

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/git-source-control#190]
Saw weird behavior when reviewing with customer (@mdavidovichHst) - looked like it was skipping a bunch of valid routines and said ".routinename.Mac was exported" when it really wasn't.

**Comment by isc-tleavitt** [comment]
We were unable to reproduce this issue - likely fixed by changes since 2022 (specifically thinking about our sweeping changes for mapping determination).

**Comment by mdavidovichHst** [comment]
@isc-tleavitt thanks Tim.  I don't even remember this issue but thanks for looking into it!
