### ISSUE TITLE
Installation fails w/ "Activate FAILURE"

### ISSUE THREAD

**Issue by copperschnack** [intersystems/git-source-control#219]
Hi,

when trying to install, I get the following error:

```
%SYS> zpm 0.5.1
https://pm.community.intersystems.com - 1.0.6
zpm:USER>install git-source-control
 
[USER|git-source-control]       Reload START (C:\InterSystems\IRIS\mgr\.modules\USER\git-source-control\2.0.5\)
[USER|git-source-control]       Reload SUCCESS
[git-source-control]    Module object refreshed.
[USER|git-source-control]       Validate START
[USER|git-source-control]       Validate SUCCESS
[USER|git-source-control]       Compile START
[USER|git-source-control]       Compile SUCCESS
[USER|git-source-control]       Activate START
[git-source-control]    Activate FAILURE
ERROR! Running command returned error.
zpm:USER>quit
 
USER>w $zv
IRIS for Windows (x86-64) 2022.1 (Build 209) Tue May 31 2022 12:27:55 EDT
```

Any hints on where I could start debugging?

**Comment by isc-tleavitt** [comment]
Unfortunately this is broken pending a Package Manager release with https://github.com/intersystems/ipm/pull/358. I'll lobby for that some more...

**Comment by isc-tleavitt** [comment]
As a workaround, you could pull down the latest package manager code from https://github.com/intersystems/ipm and install that. But we need to get an official release out.

**Comment by isc-tleavitt** [comment]
@copperschnack ipm 0.5.2 fixes the issue and was just released: https://github.com/intersystems/ipm/releases/tag/v0.5.2

**Comment by isc-tleavitt** [comment]
@copperschnack 0.5.2 is really fully completely released now. :)

**Comment by copperschnack** [comment]
Thanks, my test installation was successful now
