### ISSUE TITLE
Add source-control support for business rules

### ISSUE THREAD

**Issue by evshvarov** [intersystems/git-source-control#223]
Currently there are no source control elements visible:
<img width="1391" alt="Screenshot 2023-01-15 at 3 33 28 PM" src="https://user-images.githubusercontent.com/2781759/212538231-2079f9a6-6453-465e-883e-97c59081dfe9.png">

**Comment by isc-tleavitt** [comment]
@evshvarov this sounds like an issue with the new business rule editor, not git-source-control. :(

**Comment by isc-tleavitt** [comment]
I've filed an issue report on this internally (ref: DP-419899). Nothing can be done here in the meanwhile, so I'm just closing the issue.

**Comment by evshvarov** [comment]
Thank you!

**Comment by isc-tleavitt** [comment]
Actually closing it.

**Comment by isc-tleavitt** [comment]
I'm bad at GitHub.
