### ISSUE TITLE
Avoid fatal: bad revision HEAD in Git WebUI on empty repo

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/git-source-control#228]
This is a likely situation if you've run git init and haven't committed anything yet.

**Comment by isc-tleavitt** [comment]
@isc-pbarton this would be a nice thing to have before Summit too (just thinking about the new-user experience)

**Comment by isc-rsaptars** [comment]
Needed some clarifications:
I get this error when I initialize an empty git directory through the Configure() workflow. Is there any other workflow in which `git init` is used to create an empty git directory?
I have fixed the `Configure()` workflow by added an empty initial commit after the directory is created.

**Comment by isc-tleavitt** [comment]
@isc-rsaptars I think that's sufficient.
