### ISSUE TITLE
Server Side Source Control option is not available in Rule Editor (2022.2)

### ISSUE THREAD

**Issue by Noggin79s** [intersystems/git-source-control#240]
The Business Rule editor moved from Zen to a new Rule Editor, and I noticed that the GIT plugin is not available on the New Editor.

![image](https://user-images.githubusercontent.com/29753377/217057854-f84d50e6-c997-4ea3-b8f0-bff3325939de.png)

**Comment by isc-tleavitt** [comment]
This has already been reported and escalated to the relevant team in InterSystems; see #223. (There's nothing that can be done about it in git-source-control itself.)
