### ISSUE TITLE
Changes in BP Designer cannot be commited when using IRIS Studio

### ISSUE THREAD

**Issue by a-schuetz** [intersystems/git-source-control#241]
When changes to a BPL are made via the Business Process Designer in IRIS Studio and saved, those changes are not replicated to the Git folder in the filesystem. Therefore the changes can't be commited. When the BP Designer is used via Browser in the Management Portal it works fine.

A workaround in IRIS Studio is to remove the file from SC and add it again. Then changes will be synced to the folder once.

Steps to reproduce:
1. Open a BPL in IRIS Studio (Workspace -> Business Processes)
2. Make any change to a BPL that is already added to SC (e.g. add an annotation) and click the save button.
3. Try to commit the change. You will also notice that the change has not beend synched to the .cls file in the Git folder.

**Comment by isc-tleavitt** [comment]
@a-schuetz what IRIS version do you see this on?

**Comment by isc-tleavitt** [comment]
(I'm looking to figure out if this is an issue in Studio or git-source-control. I suspect git-source-control because I know Studio BPL/DTL works with at least one other extension I'm aware of.)

**Comment by a-schuetz** [comment]
@isc-tleavitt It was able to see it on 2022.1, 2022.2 and 2022.3. But it seems like you already found the issue 👍
