### ISSUE TITLE
Support source control of mapping configuration

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/git-source-control#248]
The configuration that determines the mapping between InternalName and filesystem structure should itself be source controlled. (And changes to it must be reflected as a first priority in pull event handlers/import/etc.)

In a package manager context, this is irrelevant; module.xml defines the mapping.

**Comment by isc-pbarton** [comment]
Other configuration settings that should be source controlled:

- Pull Event Class
- % Replacement on Export
- Mappings
- Production Decomposition

**Comment by isc-tleavitt** [comment]
This should also support parameter expansion of the environment as implemented in #124
