### ISSUE TITLE
Set up default mappings with SourceControl.Git.Settings

### ISSUE THREAD

**Issue by isc-pbarton** [intersystems/git-source-control#250]
Say I am configuring an instance programmatically with a setup script using the SourceControl.Git.Settings API:
```
set settings = ##class(SourceControl.Git.Settings).%New()
do settings.%Save()
```
Most settings values are set to a default value, but the mappings are not set to anything. Instead I have to set each mapping individually on the Mappings property.
To make this more convenient we could check if there are any existing mappings configured. If not, set Mappings to the default values.

**Comment by isc-tleavitt** [comment]
Relates to #225 re: backward-compatibility "if no mappings are configured" - might make sense to tackle simultaneously.

**Comment by isc-rsaptars** [comment]
Fixed
