### ISSUE TITLE
CSP Mapping not working when pulling / importing files.

### ISSUE THREAD

**Issue by a-schuetz** [intersystems/git-source-control#251]
CSP files are not mapped/imported correctly. CSP files are exported and pushed to the Git repository correctly, but the other way around doesn't work. When pulling / importing files the are copied to the wrong place. 

Possibly the issue might have to do with the correct use of slashes. I tried replacing '/' with '\' in the mapping and also a mixture of both, But I couldn't figure out a working combination. Mostly to the files get imported to the csp root folder of the namespace.

**Comment by isc-tleavitt** [comment]
@a-schuetz could you share the mappings you're using that lead to this?
