### ISSUE TITLE
IRIS Studio export default path wrong when git-source-control is installed

### ISSUE THREAD

**Issue by a-schuetz** [intersystems/git-source-control#252]
After installing git-source-control the default export path in IRIS Sutdio is partially using the wrong typ of slash in the path when exporting a class (sorry for the German screenshot):
 
<img width="857" alt="iris_studio_export" src="https://user-images.githubusercontent.com/12963498/228771851-b971687d-e971-4fba-a9fd-18e34b7a9e4b.png">

After removing git-sourcre-control the issue doesn't occur.

**Comment by isc-tleavitt** [comment]
That's very strange, I didn't know source control classes tied in to that dialog but seems they do. Probably just need to normalize the path at some point. (ExternalName maybe?)
