### ISSUE TITLE
Add push button to Git Ui

### ISSUE THREAD

**Issue by a-schuetz** [intersystems/git-source-control#253]
It would be nice to have a Push button in the Git Ui. Maybe under the current active branch similar to the Checkout, Merge and Delete button.

<img width="318" alt="Bildschirm­foto 2023-03-30 um 10 16 34" src="https://user-images.githubusercontent.com/12963498/228773844-6a7d25d0-642f-44ad-9fa0-fe9b558fab76.png">

**Comment by isc-tleavitt** [comment]
Agreed - this is actually a duplicate of #128. I'm going to close #128 in favor of this one since it's user-reported.
