### ISSUE TITLE
No feedback on the Git Push option in source control menu

### ISSUE THREAD

**Issue by isc-pbarton** [intersystems/git-source-control#256]
If I click the "Push to remote branch" option in the source control menu, there is no feedback to let me know whether or not it actually succeeded in pushing.

**Comment by isc-tleavitt** [comment]
@isc-pbarton this should show up in Output (location will vary - there's an icon for management portal editors, and the new rule editor has a separate item at the end of the menu to view output)

**Comment by isc-tleavitt** [comment]
Discussed with Pravin - closing. (The output is where it's supposed to be.)
