### ISSUE TITLE
while installed VSCode reports the versions differences between client and server for every change

### ISSUE THREAD

**Issue by evshvarov** [intersystems/git-source-control#264]
I see this popup window with EVERY VSCode change in ObjectScript file which is under git-source-control
<img width="784" alt="Screenshot 2023-06-19 at 2 16 19 PM" src="https://github.com/intersystems/git-source-control/assets/2781759/5cd3b03f-3aae-4f5a-9de8-fbe62fa7fd67">

**Comment by isc-tleavitt** [comment]
What's your VSCode setup? I'd assume you're not using isfs?

**Comment by evshvarov** [comment]
No. client editing with iris in docker

**Comment by evshvarov** [comment]
E.g. this repo <https://github.com/evshvarov/openai-telegram-bot> has the
issue

**Comment by isc-tleavitt** [comment]
I think this is happening because our export of the file (server-side) adds a newline at the end. If we can keep that from happening it should fix the problem.

**Comment by isc-tleavitt** [comment]
More detail on the use case:
This happens when editing a file on the instance's filesystem (rather than over isfs) when the server is configured to re-export to the same file that's being edited. git-source-control should work seamlessly in this case.
