### ISSUE TITLE
Custom PullEventHandler lost when saving Git Project Settings

### ISSUE THREAD

**Issue by copperschnack** [intersystems/git-source-control#267]
Steps to reproduce:

- Specify custom pull event class extending `SourceControl.Git.PullEventHandler.Default` w/ some write output in `OnPull()` during
`d ##class(SourceControl.Git.API).Configure()`

- Pull change from git upstream to verify that the output is shown
- Open `Git > Settings` and save
- Pull other change from git upstream - custom pull handler is no longer in place

**Comment by isc-tleavitt** [comment]
@copperschnack good find, thanks for reporting this.

**Comment by isc-tleavitt** [comment]
Solution: Settings UI needs to dynamically populate the dropdown based on existing subclasses of SourceControl.Git.PullEventHandler (see %Dictionary.ClassDefinition:SubclassOf) rather than being hardcoded to the two we ship.
