### ISSUE TITLE
-2 as a timestamp for some items

### ISSUE THREAD

**Issue by eduard93** [intersystems/git-source-control#275]
When trying to do a force import I'm getting an error:
```
Error invoking Source Control:
ERROR #5002: ObjectScript error: <VALUE OUT OF RANGE>zGetTempFileAndRoutineTS+7^SourceControl.Git.Utils.1
```

This is caused by: `GetTempFileAndRoutineTS` method, line `set routineTSH = $zdatetime(routineTSH,3)`

`routineTSH` is `-2` as returned by `RoutineTSH`, which gets it directly from the global:
```
IRIS:EDUARD>zw ^SYS("SourceControl","Git","TSH")
^SYS("SourceControl","Git","TSH","Ens.Config.DefaultSettings.esd")=-2
^SYS("SourceControl","Git","TSH","EnsExportNotes.EnsExportProduction_2021-03-25 16-21-00_981-4.ptd")=-2
```
Other items in a `"SourceControl","Git","TSH"` subscript have normal `$h` values, i.e. `65579,34208.94009339`.

I have added a temporary workaround to `RoutineTSH`:
```
#dim tsh = $case(type,"csp":"",:$get(@..#Storage@("TSH", ..NormalizeExtension(InternalName))))
set:tsh=-2 tsh=0
```

But I'm not sure where exactly `-2` is coming from.

**Comment by isc-tleavitt** [comment]
Today I learned that %File:GetFileDateModified might return an OS-level error code instead of a timestamp! In this case, -2 means:

USER>w $zu(209,2)
<2> No such file or directory

(On Windows, it'd be -3.)

I'll file a Jira to get the documentation fixed. In the meanwhile, are your mappings configured correctly?

**Comment by eduard93** [comment]
I think mappings are configured correctly, but there are no mappings for `esd`, `ptd`.

**Comment by isc-tleavitt** [comment]
@isc-rsaptars let's just add the same workaround for this case.
