### ISSUE TITLE
Failure to add item to source control after removing it

### ISSUE THREAD

**Issue by isc-pbarton** [intersystems/git-source-control#276]
Steps to reproduce:

Use VS Code to add a new class to a namespace enabled for git-source-control. See in output that it is exported to the working directory.

Choose "Remove" from the server-side source control menu. The file is deleted, but the "git rm" fails because we never issued a "git add": 
```
C:\temp\TESTGIT2\cls\Test\Class1.cls for Test.Class1.CLS deleted
fatal: pathspec 'C:\temp\TESTGIT2\cls\Test\Class1.cls' did not match any files
```

Now we are in a state where there is no way to add the file to source control. If I try to delete the class in VS Code, it fails with:
```
ERROR #5001: File does not exist - C:\temp\TESTGIT2\cls\Test\Class1.cls
```
The workaround is to make an edit to the class in VS Code and compile so it reexports. Then open the Git Web UI and add it to the staging area.

**Comment by isc-tleavitt** [comment]
@isc-pbarton I can't reproduce this one. Can you try again and see if there's a step you're missing from the description?

**Comment by isc-pbarton** [comment]
I am also not able to reproduce this one anymore. I will close the issue.
