### ISSUE TITLE
Error on checkout with branch name containing slash

### ISSUE THREAD

**Issue by zdateh** [intersystems/git-source-control#295]
![image](https://github.com/intersystems/git-source-control/assets/103598862/ecbf3d6d-a692-4cc6-9f2b-f29f3869f73f)

The full error is:

```
M	rtn/saCLN05.mac

fatal: cannot lock ref 'refs/heads/feature': 'refs/heads/feature/smxc_latest' exists; cannot create 'refs/heads/feature'
```

The modified *.mac I know about, but git would normally be fine with branchcheckout when a file is modified. It looks like the branchname is causing a fatal severe error. The branch being checked out via the studio Git UI is
`feature/chgNNNNNN_some_description`
The error mentions another branch 
`feature/smxc_latest`
which also exists in the repo, but wasn't checked out immediately previously. My guess is the slash is confusing the scripts in some way, causing multiple branch names containing `feature/*` to clash in some way? Just my guess!

Doing the checkout of the same branch via Git bash works fine:
```$ git checkout feature/chg0172358_contact_detail_BEDs
Switched to a new branch 'feature/chg0172358_contact_detail_BEDs'
M       rtn/saCLN05.mac
branch 'feature/chg0172358_contact_detail_BEDs' set up to track 'origin/feature/chg0172358_contact_detail_BEDs'.
```

Thanks,
Chris

**Comment by isc-tleavitt** [comment]
@zdateh could you grab the full git command being run from (e.g.) the audit database?

**Comment by zdateh** [comment]
It seems to run many O/S commands recorded separately in the audit when using the UI, but I think it's this one (censored out some PID):

```
Execute O/S command
Directory: g:\nbss\cache\dev_cb_app\
Command: "C:\Program Files\Git\bin\git.exe" -C C:\SOURCECONTROL\DEV_CJB\database\ -c "core.sshCommand=ssh -F /dev/null -o StrictHostKeyChecking=accept-new -i C:\\Users\\My.Name\\.ssh\\id_rsa" -c user.name=My.Name -c user.email=myemail@website.com -c color.ui=true checkout -b feature origin/feature/chg0172358_contact_details_from_bs_select
Flags: /SHELL /STDOUT="C:\Users\other.name\AppData\Local\Temp\Jg6n98us"
/STDERR="C:\Users\other.name\AppData\Local\Temp\T9nxSibG"
```

Perhaps the slashes need escaping in the branch name?
