### ISSUE TITLE
Issues with incremental load strategy

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/git-source-control#30]
Needs to:
* handle deletes
* only consider diffs on the current branch (currently does an incremental load for every file reported by git fetch even if it's on a different branch, it seems?)

**Comment by isc-svelury** [comment]
To clarify, the fetch and diff work on the repository as a whole. However, git pull only fetches and merges changes for the current branch. So even if files from other branches are reported in git diff, it won't affect the end result of the Pull() event handler.

However, it would be better to ensure the fetch and diff in Pull() work only on the current branch.

**Comment by isc-tleavitt** [comment]
@isc-svelury thanks. Feel free to split off handling of deletes as a separate issue or address all at once if you prefer.
