### ISSUE TITLE
Suppress editing of other user's locked classes via VSCode and Management Portal as early as possible

### ISSUE THREAD

**Issue by isc-adepedro** [intersystems/git-source-control#301]
Suppress (editing of files in a locked environment, editing of files locked by another user) via VSCode and Management Portal (test specifically for production) as early as possible.

* VSCode allows to start editing the class.
* When attempting to save the class, an error is shown (that it is not possible to save/compile it)
* But the user still sees the file as changed
  * (by closing the file and opening the file again the changes are not there anymore though)

**Comment by isc-tleavitt** [comment]
Note: could take a similar approach to %Studio.SourceControl.ISC "attempted edit of read-only file" action to do this.
