### ISSUE TITLE
Add support for git submodules

### ISSUE THREAD

**Issue by Antoine-dh** [intersystems/git-source-control#305]
I use modules for different namespaces in my project setup as git submodules
Consider the following directory tree:

```.
├── .git/ //main git directory
├── .gitmodules
└── modules/
    ├── ModuleA/
    │   ├── .git //git submodule A
    │   └── module.xml
    └── ModuleB/
        ├── .git //git submodule B
        └── module.xml
```

The problem I suppose is that sources are not correctly mapped because the package manager is looking for a **directory** named ".git" at the root of the module folder, however submodules are just simple files linking to the parent git directory

according to this line:
https://github.com/intersystems/git-source-control/blob/9aa8009111a14328118e0dcfef02cd7b3101a1e6/cls/SourceControl/Git/PackageManagerContext.cls#L27C1-L27C166

exemple .git file in a submodule:

```
$ cat modules/ModuleA/.git 
gitdir: ../../.git/modules/modules/ModuleA
```

**Comment by isc-tleavitt** [comment]
Thanks - I have someone working on the milestone this is in starting Monday. I think you're just right though; feel free to submit a PR.
