### ISSUE TITLE
Document recommended use patterns

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/git-source-control#32]
Specifically, should cover:

## Conceptual:
single vs. multi-developer (including namespace segmentation for shared environments as is commonly used in HCC)
remote vs. local instance and interaction with local git command line / GUI clients re: synchronization with IRIS

## Installation/Setup:
Initial setup - new repository
Initial setup - linking to existing repository

## Recommended workflow by persona:
"Hi, I'm an Interface Engineer. What's Git?": Hybrid approach with per-developer namespace, basic mode, main DEV namespace, deployment manager DEV->TEST and TEST->LIVE
"I'm an interface engineer, but this isn't my first CICD rodeo": Trunk-based strategy (with some coverage/material on GitLab and workflows)
Software developer: adapting to different workflows (e.g. [gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)), advanced use with package manager, local dev / containers

# Priority list:
## HCC use cases:
- [x] Development workflow for Health Connect Cloud: basic mode, feature branch, merge request to development, git pull in shared development namespace (all via management portal)
- [ ] Initial setup for Health Connect Cloud: mapping configuration and "Import All (Force)" (all via management portal)
- [ ] Trunk-based strategy and CICD flow for Health Connect Cloud (changes get to dev/test/live via pipeline)

## Developer use cases:
- [ ] Use with standard branching/merging strategy
- [ ] Use with VSCode
- [ ] Use with package manager
- [ ] Use with local dev environment / containers

## Conceptual topics:
- [x] Conceptual introduction to source control / change control
- [ ] Conceptual: single developer vs. multi-developer
- [ ] Conceptual: remote vs. local instance and interaction with local git command line / GUI clients re: synchronization with IRIS

**Comment by isc-svelury** [comment]
Also include a start-up guide and a high-level usage and feature guide.

**Comment by isc-tleavitt** [comment]
Should also cover basic mode for the common Health Connect use case
