### ISSUE TITLE
Slow Production load with set up git

### ISSUE THREAD

**Issue by SRFTInterface** [intersystems/git-source-control#331]
Recorded in WRC# 986463. 
Issue is after setting up Git and Azure using SSL key production monitor page slowed down from a <1 second load to a 6-10 second load

**Comment by isc-tleavitt** [comment]
@SRFTInterface FYI, we have a new release coming very soon (v2.3.1) which addresses some performance issues. I suspect it could fix this too.

**Comment by isc-tleavitt** [comment]
@SRFTInterface I've just published version 2.3.1 - can you see if that addresses the issue?

**Comment by SRFTInterface** [comment]
Hi, we have had a few other issues today- initially it looks like it loads up fast. The GIT GUI in tie workspace is not showing changes when add to git- working when using gitextensions on the user running ensemble with the ssh rights 
![image](https://github.com/intersystems/git-source-control/assets/166516616/9ec55ea0-8b76-4498-9a12-d548fbb63615)
![image](https://github.com/intersystems/git-source-control/assets/166516616/4a4f3639-14d6-4ea9-b872-e953c39fb75f)

**Comment by isc-tleavitt** [comment]
@SRFTInterface is this after updating to 2.3.1?

**Comment by isc-tleavitt** [comment]
@isc-pbarton can you take a look at this?

**Comment by SRFTInterface** [comment]
@isc-pbarton to confirm that the array has current user changes if i'm looking at it , i don't know much about .js really but at least means it knows somewhere there are changes to display 
![image](https://github.com/intersystems/git-source-control/assets/166516616/d626fb41-5d5d-43d4-b661-71b297ae0d88)

**Comment by isc-pbarton** [comment]
@SRFTInterface I haven't been able to replicate this so far but will try some more options tomorrow. In the meantime could you try clearing your web browser's cache to see if that makes a difference? Also if you are able to provide detailed steps to replicate the error that would be very helpful.

**Comment by SRFTInterface** [comment]
I just ZPM installed the new version and on my understanding started to add classes via studio or VS code to the repo. I cleared now that was new to git.Remove() everything from source and still get the new issue. 
![image](https://github.com/intersystems/git-source-control/assets/166516616/1422a058-5efc-49d5-a4b5-41b5e220ca61)

Is there a clean way to remove the code and reinstall? I would be tempted to reinstall the webui from stratch again and see if something got mismatchd between versions?

**Comment by SRFTInterface** [comment]
@isc-pbarton when i use the old WebUIDriver.cls it works 
![image](https://github.com/intersystems/git-source-control/assets/166516616/2c54fd4e-ba72-4a95-8b6f-da43b73578d8)

I have noticed if i change the line 
 
    set fileToOtherDevelopers ={}
to
 set fileToOtherDevelopers =[] 
using the new git control it works for me (not checked if other devs changes populate in)
This then works. 
Using Windows.

**Comment by isc-pbarton** [comment]
@SRFTInterface Thank you for the screenshots. It does like like you have the older version of the Web UI running, and it's conflicting with the newer version of the ObjectScript code. Could you try uninstalling and then reinstalling the package?
```
zpm
uninstall git-source-control
install git-source-control 2.3.1
```

Another thing to try might be clearing the CSP gateway cache.
`set registry = $system.CSP.GetGatewayRegistry() set gateways = registry.GetGatewayMgrs() for no=1:1:gateways.Count() do gateways.GetAt(no).ClearCache()
`

**Comment by SRFTInterface** [comment]
Thanks, needed to be disabled first before uninstalling and installed second time via the studio command as is the setup notes. Speed is much much improved
