### ISSUE TITLE
Modified files not showing in "Working Copy" section in UI

### ISSUE THREAD

**Issue by jbglytec** [intersystems/git-source-control#336]
After making changes to a file in the repo we are no longer seeing the changed file in the "Working Copy" section on the git UI page.

Previously it would show there to select the changed file to be staged.

We can however run a git status and see the changed file and commit from the dropdown in VSCode.

**Comment by isc-tleavitt** [comment]
@jbglytec which version of git-source-control are you running? Did you encounter this after upgrading to 2.3.1?

**Comment by jbglytec** [comment]
@isc-tleavitt How can I check the version of the plug-in?

**Comment by isc-tleavitt** [comment]
@jbglytec this'll do the trick - run in Terminal / iris session:
`zpm "list"`

**Comment by jbglytec** [comment]
@isc-tleavitt we are running v2.1.1

**Comment by isc-tleavitt** [comment]
@jbglytec there's a good chance you're encountering a bug that has since been fixed. I'd recommend updating to v2.3.1.

**Comment by jbglytec** [comment]
Upgrading resolved our issues. Unsure why things stopped working with previous versions but this is resolved.

Thanks for the help @isc-tleavitt
