### ISSUE TITLE
ObjectScript error: <FUNCTION>SetTextFromArray+94^%apiSRC after working with DTL

### ISSUE THREAD

**Issue by SRFTInterface** [intersystems/git-source-control#337]
Hi:
I'm not sure how i did it, i was working with a DTL and used "test" a lot. The item was added to SC. 
Whenever i moved an if that said 

`<if condition='source.{PV1:DischargeDisposition} = "Died" ' disabled='1' >
<true>
<assign value='"DN"' property='MethodDischarge' action='set' />
</true>
</if>`

The DTL would give weird save errors not related to this i.e. 
![image](https://github.com/intersystems/git-source-control/assets/166516616/0c70888d-fab1-46a0-ac69-dbdfdd72ea79)

it would error on saving even though dtl was fine 
![image](https://github.com/intersystems/git-source-control/assets/166516616/196182d0-8950-4a33-9302-be47893446c3)

it would give then Source control errors 
![image](https://github.com/intersystems/git-source-control/assets/166516616/701e98a8-5b2b-4f50-be7a-47d8d213d01e)

The server become unresponsive, will get the logs when it is active again

**Comment by isc-tleavitt** [comment]
This seems like there could be a general issue with available memory on the machine.

**Comment by isc-tleavitt** [comment]
@SRFTInterface it could be worth contacting InterSystems Support about this, but the root issue here is almost certainly outside of git-source-control and most likely (IMO) also outside of IRIS.

**Comment by SRFTInterface** [comment]
I will try replicate tomorrow and close if unable to replicate as a non source control issue

**Comment by SRFTInterface** [comment]
Looks like non source control issue- server issue- will be putting source control on our ramped up preprod server and will be able to see if over the months any further issues like this occur
