### ISSUE TITLE
Support merge through UI

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/git-source-control#34]
We should support merging changes from another branch through the UI

**Comment by isc-svelury** [comment]
Merges can become quite complex depending on the changes. We could check if the merge causes any conflicts and only display the option if it won't. To do that, we would still have to perform the merge but not commit or fast-forward and then abort it. We have to then parse the output to check for merge conflicts.
```
git merge --no-commit -no-ff $BRANCH
git merge --abort
```

We could merge all this into an alias like in this [thread](https://stackoverflow.com/questions/501407/is-there-a-git-merge-dry-run-option). But running merges every time we have to load the sidebar would make the whole website lag quite a bit. So maybe we should stick to merging only when the user specifically selects the option and deal with the consequences after.
