### ISSUE TITLE
Remove trailing/leading whitespace on prompt for git remote to clone from (- nd maybe more generally in Configure()

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/git-source-control#356]
From customer call today

**Comment by isc-etamarch** [comment]
@isc-tleavitt Is this still an issue? I tried running through the Configure() method and see no leading / trailing whitespace

**Comment by isc-tleavitt** [comment]
@isc-etamarch this is if the *user* provides leading/trailing whitespace in their answer to a prompt.
