### ISSUE TITLE
Some characters may not be escaped properly when committing using WebUI

### ISSUE THREAD

**Issue by raymond-rebbeck** [intersystems/git-source-control#369]
Using Release 2.3.1 with IRIS 2023.1.1.380.0 and Studio.

Entered a commit message into WebUI that used a '&' character and was able to stage and commit without apparent issue however when reviewing the git log of the branch immediately after, the commit message was cut off from that character onwards, suggesting that the text may not be getting escaped properly when the commit is performed.

**Comment by isc-tleavitt** [comment]
Good find, we'll take a look. There are a few higher priorities at the moment but this is concerning so should slot in for the short term.
