### ISSUE TITLE
Instance-wide awareness of uncommitted queue for concurrency

### ISSUE THREAD

**Issue by isc-hwojnick** [intersystems/git-source-control#370]
instance-wide awareness of uncommitted queue for concurrency warnings/blocks across developers working in separate feature branches/namespaces.

**Comment by isc-tleavitt** [comment]
Should add a class query that looks across namespaces and gets the branch and all uncommitted changes for each namespace. See: https://docs.intersystems.com/iris20242/csp/docbook/DocBook.UI.Page.cls?KEY=GOBJ_queries_userqueries
