### ISSUE TITLE
Add default dev branch to settings

### ISSUE THREAD

**Issue by isc-hwojnick** [intersystems/git-source-control#392]
This default dev branch would be used for automatically opening a browser link for a merge into the dev branch instead of live.

Alternatively, instead of labeling this as dev, we could allow users to in their settings add a custom number of branches that they use for their release pipeline, just like how mappings are able to be added. Users could have a "dev", "test" and then "live" branch added to the settings. This could be useful for allowing them to work through the trunk based strategy through the git-source-control tool.

**Comment by isc-tleavitt** [comment]
IMO the strategy for merging should be managed in the remote (e.g., GitLab) rather than via the extension itself.

Closing this as the solution is going to be very specific to the remote being used.
