### ISSUE TITLE
Add maximum length to commit message in web UI

### ISSUE THREAD

**Issue by isc-pbarton** [intersystems/git-source-control#406]
The placeholder text for commit message in the web UI says "72 character limit", but there is no actual enforcement of this limit. I can add a commit message as long as I want and commit without issue. We probably want to add a maxlength to this input just because a shorter commit message is good practice.

**Comment by raymond-rebbeck** [comment]
I would like it if the limit was both optional and configurable, to suit the needs of different teams and workflows. There seem to be differing opinions online as to what best practices are for git commit limits such as the '50/72' rule suggestion.
