### ISSUE TITLE
New items should be automatically added to source control in Basic Mode

### ISSUE THREAD

**Issue by isc-pbarton** [intersystems/git-source-control#407]
If I add a new item through Studio / VS Code / Interoperability portals / wherever, and I use the Sync option, that new item is not committed unless I explicitly add it to source control. In Basic mode, new items should get automatically added to source control.

**Comment by isc-tleavitt** [comment]
As part of this, need to see if an auto-created new business rule gets automatically added and create an upstream Jira if not
