### ISSUE TITLE
Configure doesn't set source control class on first run

### ISSUE THREAD

**Issue by isc-pbarton** [intersystems/git-source-control#443]
The very first time you install and configure git-source-control in a namespace, it does not set SourceControl.Git.Extension as the source control class for the namespace. If you run Configure() a second time after that it will set it properly.

**Comment by isc-tleavitt** [comment]
@isc-pbarton - @isc-akadoo was unable to reproduce this issue. From code inspection it seems that Ctrl+C'ing out (or equivalent) will roll back the transaction with all configuration changes, including setting the source control class. I'd call this a feature. Is there some detail we're missing?

**Comment by isc-pbarton** [comment]
Thank you both for looking into it - I also cannot reproduce this now. Closing the issue.
