### ISSUE TITLE
Basic mode create new branch should do so from main

### ISSUE THREAD

**Issue by isc-hwojnick** [intersystems/git-source-control#452]
Because basic mode revolves around a specific use pattern, we should make it so creating a new branch through the menu in basic mode does so after first switching to the main branch and pulling

**Comment by isc-akadoo** [comment]
In the [case](https://github.com/intersystems/git-source-control/blob/d18dd40eecafe8cf47c88844971a644297a13c32/cls/SourceControl/Git/Utils.cls#L359) where basic mode is set and the default merge branch is declared, currently the new branch is created from the defaultMergeBranch, by first switching to the default merge branch and pulling.

Need clarification on what should the behavior be in the case where the defaultMergeBranch is not declared.

**Comment by isc-tleavitt** [comment]
It looks like @isc-hwojnick implemented this a little over a month before filing this issue! Hooray.

We'll file another issue to improve/clarify the UX outside of basic mode for a more GitHub Desktop-like experience.
