### ISSUE TITLE
Untick All on GIT GUI prompting will update files not selected that are not your changes will be pushed 

### ISSUE THREAD

**Issue by SRFTInterface** [intersystems/git-source-control#478]
We have a bunch of changes multiple users 
![image](https://github.com/user-attachments/assets/09764353-4f69-415f-8328-9cb83fe09ff8)
 If you select all then unselect all 
Then just have one file selected to push 
![image](https://github.com/user-attachments/assets/38c8fcf8-96b2-4324-a368-7eb1ca8c5104)

The Confirm comit still says it will send through other files

![image](https://github.com/user-attachments/assets/e526c07b-79ad-4963-a837-c04641d714f0)

Some of these are a bit odd as cached error but TI is for instance a normal file 
![image](https://github.com/user-attachments/assets/86afe506-aa1f-47f7-b9fe-57d6de97fa4f)

**Comment by isc-tleavitt** [comment]
@isc-akadoo could you look into this next?
