### ISSUE TITLE
Failure to commit through web-ui after deleting added file

### ISSUE THREAD

**Issue by isc-pbarton** [intersystems/git-source-control#481]
Steps to reproduce:

1. Run a baseline export without committing: do ##class(SourceControl.Git.API).BaselineExport("")
2. Confirm in the Git WebUI that some files were added to source control
3. From the file system, delete one of the added files.
4. In the Git WebUI, check "select all files" and attempt to commit. 

I get an error message:
```
error: pathspec 'cls/pbarton7/test50.cls' did not match any file(s) known to git
```

The use case this might be an issue for is if I have a large baseline export, but there are some files I don't want included so I delete them from the file system. This puts us into an edge case where committing should work but does not.

**Comment by isc-tleavitt** [comment]
I don't see this as high priority because you need to delete from the filesystem. Re-running git status (which happens in a bunch of different ways) should clear things up in the uncommitted queue. If it doesn't then I'd bump the priority on this to Q3/Q4.

**Comment by isc-tleavitt** [comment]
@isc-pbarton we saw this on our customer call Wednesday afternoon, so upped priority.
