### ISSUE TITLE
In basic mode, prohibit commits to default merge branch

### ISSUE THREAD

**Issue by isc-pbarton** [intersystems/git-source-control#484]
If we are in basic mode and have a default merge branch configured (call it "development"), there should never be commits from git-source-control directly into development. A couple of scenarios where this could happen and lead to issues:

- I switched back to the development branch after finishing a feature and started working on a new feature but forgot to create a new feature branch
- I tried to create a new feature branch but it failed for some reason. I assume I'm on the new branch because I didn't check source control output, but I'm actually on development.

If the current branch is development, the sync option should not add, commit, or push. It should just pull.

**Comment by isc-tleavitt** [comment]
This ends up being pretty bad because branches can end up diverging and the situation is impossible to resolve without e.g. running classmethods. Added to Q3/Q4 milestone.
