### ISSUE TITLE
Possible issues with differing file extensions on HL7 between VSCode and Management Portal

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems/git-source-control#495]
I've observed in my own testing and in review of a customer call recording some possible differences in behavior / issues related to HL7 file extensions being inconsistent with editing from different places. Because of OS-level differences this is something that would only end up mattering on Linux, of course.

I think the root cause / solution might end up being similar to https://github.com/intersystems/ipm/issues/527

**Comment by isc-tleavitt** [comment]
The issue seems to be that .HL7 (upper case) isn't properly recognized as the right document type.

**Comment by isc-etamarch** [comment]
I've noticed that the internal name mostly used .CLS (sometimes .cls), while external name is usually .cls. Probably not causing the HL& issues as you noted above, but could also potentially cause issues
