### ISSUE TITLE
Sync operation does not properly handle file rename

### ISSUE THREAD

**Issue by isc-pbarton** [intersystems/git-source-control#496]
For example, on a remote repository rename an HL7 schema with extension .HL7 to have extension .hl7. Configure Basic mode on an IRIS instance so sync will merge changes from that branch on the remote repository. Running the Sync operation does not properly import the new .hl7 file.

**Comment by isc-etamarch** [comment]
@isc-pbarton I think that this was resolved with PR #508, though want to make sure that you aren't seeing the issue anymore

**Comment by isc-tleavitt** [comment]
@isc-etamarch this is a distinct issue. If you change the file extension the git pull output will have something like:
/data/hl7/{Foo.HL7 -> Foo.hl7}
Which we need to interpret as "Foo.HL7 (in the database) was modified"

This could potentially be trickier, like:
/data/hl7/{Foo.HL7 -> Bar.hl7}
Which we would need to interpret into internal names as "Foo.HL7 was deleted, Bar.HL7 was added."
