### ISSUE TITLE
Deleting deleted files on Import All fails

### ISSUE THREAD

**Issue by isc-etamarch** [intersystems/git-source-control#524]
When running import all, run into an error that a file that has already been deleted (before the import) has failed to be deleted. This occurs on both the Management Portal and VSCode extension.

Error:

ERROR #5019: Cannot delete file '/data/db/mgr/repo/ETAMARCH/testfile.xml' [e^Delete+16^%CSP.Routine.1^2 e^DeletePage+3^%SYSTEM.CSP.1^1 e^DeleteFile+12^SourceControl.Git.PullEventHandler.IncrementalLoad.1^1 e^OnPull+8^SourceControl.Git.PullEventHandler.IncrementalLoad.1^1 e^OnPull+4^SourceControl.Git.PullEventHandler.Default.1^1 e^ForModifications+4^SourceControl.Git.PullEventHandler.1^1 e^ImportRoutines+50^SourceControl.Git.Utils.1^1 e^ImportAll+1^SourceControl.Git.Utils.1^1 e^UserAction+41^SourceControl.Git.Utils.1^1 e^UserAction+39^SourceControl.Git.Extension.1^1 e^UserAction+13^%Studio.SourceControl.Interface.1^1 e^UserActionExecute+11^%Atelier.v1.Utils.Extension.1^1 e^UserActionFunc+2^%Atelier.v1.Utils.Extension.1^1 e^%0AmBm2l1t+1^%sqlcq.ETAMARCH.cls15.1^1 d^%0AmBk1^%sqlcq.ETAMARCH.cls15.1^1 d^%Next+5^%sqlcq.ETAMARCH.cls15.1^1 e^AppendResultSet+35^%Api.Atelier.v6.1^1 e^Query+46^%Api.Atelier.v6.1^1 e^DispatchRequest+23^%CSP.REST.1^1 e^Page+26^%CSP.REST.1^1 e^zPage+2^%Atelier.REST.1^1 e^CSPDispatch+503^%SYS.cspServer^2 d^CSPDispatch+280^%SYS.cspServer^1 d^ProcessRequest+1^%CSP.Session.1^1 d^Request+683^%SYS.cspServer2^1 d^Request+25^%SYS.cspServer2^1 d^ProcessRequest+1^%CSP.Request.1^1 d^css+21^%SYS.cspServer2^1 d^Server+64^%SYS.SERVER^2 d^^^0:ETAMARCH]
WARNING: Deletion of /data/db/mgr/repo/ETAMARCH/testfile.xml failed.

**Comment by isc-tleavitt** [comment]
Some of the issues we saw were related to the web application editing mode introduced in 2.5.0

**Comment by isc-tleavitt** [comment]
The solution here is, in general, to not indicate an error if a file would be deleted but doesn't exist.
