### ISSUE TITLE
Popping from stash (with merge conflict) causes issues

### ISSUE THREAD

**Issue by isc-etamarch** [intersystems/git-source-control#531]
Based on customer feedback

If popping changes from stash results in a merge conflict, the GitUI errors out, and the production is left in a broken state (in merge conflict state). There is no way to fix this through the UI, only manually fixing the merge conflict in the code. 

We need to allow for a way to resolve the merge conflict without going directly into the code.

@isc-tleavitt What are your thoughts?

**Comment by isc-tleavitt** [comment]
I think the right option would be:
Attempt production configuration auto-resolve
If that fails, cancel the stash pop/apply (ideally preserving the stash?)

This is also a pointer toward recommending basic mode / per-developer namespaces to the customer.

**Comment by isc-etamarch** [comment]
This also causes the workspace view to error out. Trying to commit this change does not work, though discarding this file does not actually discard the file
![image](https://github.com/user-attachments/assets/90baea79-d716-4755-89a3-3ecb54256166)

**Comment by isc-tleavitt** [comment]
The other resolution option is to use the Web Application view of the repository, which gives you isfs access to the raw files. But we can't have that as the only/default option.
