### ISSUE TITLE
Prune tracking references to deleted remote branches

### ISSUE THREAD

**Issue by isc-svelury** [intersystems/git-source-control#58]
Currently we do not have any way to prune references to deleted branches. This means that unless the user manually runs `git fetch --prune`, references to deleted remote branches will remain, clutter up the web UI and possibly cause confusion. 

A button on the web UI next to the remote branches section header might work well?

**Comment by isc-tleavitt** [comment]
@isc-svelury I think that's a good idea - maybe just put a refresh button there.

**Comment by isc-tleavitt** [comment]
Will this mess with our diff tracking for pull?

**Comment by isc-svelury** [comment]
It shouldn't. The diff in pull will only compute the diff between the tip of the local branch and its remote reference.
