### ISSUE TITLE
Configuration for remote development

### ISSUE THREAD

**Issue by raszkiewicz** [intersystems/git-source-control#597]
How do you configure it to have source control on a namespace accessed via the InterSystem Server Manager extension? 

An example from the video explains only how it will work with a cloned git repo on a local machine (PC/Mac), but so far, I can't get it to work on a remote development server (replacing existing remote Studio via RDP with local VS Code).

**Comment by isc-tleavitt** [comment]
@raszkiewicz you can get to the menu and everything important from there via the source control icon in VSCode when you're editing over isfs (that is: in server manager, choose to edit code in a namespace):

![image](https://github.com/user-attachments/assets/fb0c6ad3-07e4-4ef8-accd-316def039dd1)

**Comment by isc-tleavitt** [comment]
And which video are you referring to?

**Comment by raszkiewicz** [comment]
@isc-tleavitt  here: https://www.youtube.com/watch?v=elVQEU9MitE

**Comment by raszkiewicz** [comment]
> @raszkiewicz you can get to the menu and everything important from there via the source control icon in VSCode when you're editing over isfs (that is: in server manager, choose to edit code in a namespace):
> 
> ![image](https://private-user-images.githubusercontent.com/73311181/381291872-fb0c6ad3-07e4-4ef8-accd-316def039dd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMzMyMDUsIm5iZiI6MTczMDIzMjkwNSwicGF0aCI6Ii83MzMxMTE4MS8zODEyOTE4NzItZmIwYzZhZDMtMDdlNC00ZWY4LWFjY2QtMzE2ZGVmMDM5ZGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDIwMTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2NTc1NzBhZmM2NDNjNjU4ZGMxZGNlNDE4NGZjY2MwMjgxNjg1NmZjZjcxMDQyNDhhYzFiMmNiNzlmNTFkZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cZ3KYnhBzPY5WP5HjlalAJetSiizNkBTAAdPyM5yCZ4)

Wow, that is way easier to handle than going over the command line. Thanks for the tip! I assume that "Temp folder for this namespace" is a developer folder with the current `.git` location from the Studio,

**Comment by isc-tleavitt** [comment]
Correct! We really should call it something better than "Temp folder" - filed an issue for that (#601)

Sounds like things are working, so I'll close this out.
