### ISSUE TITLE
Git UI JS Error in Studio when accessing Stash screen

### ISSUE THREAD

**Issue by raymond-rebbeck** [intersystems/git-source-control#609]
On current HEAD of main branch and following on from #592 I am still getting an error when accessing the Stash screen on Git UI, all that seems to have changed is the line that the error is occurring on:

![image](https://github.com/user-attachments/assets/59d86fb8-0509-4f7b-a6a0-2eeb0327c47f)

IRIS for UNIX (Ubuntu Server LTS for x86-64 Containers) 2024.1 (Build 267_2U) Tue Apr 30 2024 16:04:37 EDT

**Comment by isc-tleavitt** [comment]
@raymond-rebbeck thank you... I just tested from Windows and it seems there's some OS-dependent behavior here that needs to be corrected.

**Comment by isc-tleavitt** [comment]
Note to self: also need to make sure we haven't broken the git-command API endpoint, I missed the code duplication around the newlines there.

**Comment by isc-tleavitt** [comment]
Going to take this opportunity to clean up the git response parsing in the webui because it's absolutely disgusting and shouldn't be so sensitive to whitespace changes.
