### ISSUE TITLE
Allow SyncCommit Basic Mode feature to be turned off

### ISSUE THREAD

**Issue by raymond-rebbeck** [intersystems/git-source-control#637]
It would be great if the automatic committing of uncommitted files that is performed by the *SyncCommit* method in Basic Mode was able to be turned off.

The commit messages that it produces are not great and are not consistent with our team's development practices or expectations.

We are finding that developers who are new to Git are performing Syncs without realising that they have uncommitted files, any that they did have disappear and it's not realised what has happened until they do an eventual PR and the commits are scrutinised.

If the Sync aborted when there were uncommitted files, that would be preferable. The developer would either see that they need to do a commit or they woul dseek guidance and find out, overcoming the problem and avoiding any future headaches at the moment where it starts.

**Comment by isc-tleavitt** [comment]
@raymond-rebbeck clarifying the ask here: you want to be able to sync without committing?

The point of "Sync" is to have one button to press to commit your work, get it rebased on the latest commit on the target remote branch, and push it up so it's ready for a PR.

If you're not looking for one button to do all those things, you probably want Expert mode (not Basic).

**Comment by isc-tleavitt** [comment]
We could definitely add an option to suppress the default commit message and require the user to enter something.

**Comment by raymond-rebbeck** [comment]
I should have taken a closer look at this one before raising an issue. Looking closer into it I see now that the Sync screen in fact does show you the files that it will commit and has a (pre-filled) text field with what the commit message will be that can be modified. I was somehow mistakenly under the impression that the Sync commit was automated and didn't offer for you to enter a message. I suspect that when this has occurred on our end the users did not read or comprehend what the Sync screen was telling them and just clicked Sync.

I think that an option to suppress the default message and require the user to enter something would be helpful. Wouldn't be a bad idea in my opinion to have the optional commit details able to be specified too, perhaps even as another option. Our users are currently committing in the Workspaces screen of Git UI (generally using both message and details) and then doing a Sync, predominantly for the fact that it does rebase and push.

**Comment by isc-tleavitt** [comment]
Thank you @raymond-rebbeck - I'm going to fold these ideas into #623 and close this issue out.
