### ISSUE TITLE
Add button to migrate production to/from decomposed format

### ISSUE THREAD

**Issue by isc-pbarton** [intersystems/git-source-control#645]
As a developer on an IRIS Interoperability system, I want to change the "decompose productions" settings and then migrate all existing productions in source control to the new (decomposed or recomposed) format. Currently I can do this in terminal by calling the `BaselineProductions` API method. There should also be a button on the Settings page right next to the "decompose productions" setting that will allow me to do this without terminal access.

**Comment by isc-tleavitt** [comment]
Goes in the menu instead - that's fine. I think #666 resolves this.
