### ISSUE TITLE
git on AIX not found

### ISSUE THREAD

**Issue by CraigRegester** [intersystems/git-source-control#69]
After fresh install using zpm, specified path to git as /usr/bin/git:

cacheusr@oairsint1:/home/cacheusr$ /usr/bin/git --version  (showing explicit path here w/ version output)
git version 2.31.1
cacheusr@oairsint1:/home/cacheusr$ git --version (but git is in search path)
git version 2.31.1

However, settings UI doesn't seem to like it. 

![image](https://user-images.githubusercontent.com/65192819/141834423-46f71187-ab04-4bac-b36b-b1add932ecea.png)

Just digging into all of this but didn't see any known bugs/issues, so just wanted to share as I found something. Thanks for all your work on this @isc-tleavitt and others. Hoping to incorporate/merge (hah) this with my own git/github source control.

---

@isc-tleavitt notes:
Root cause: the namespace temp folder didn't exist. This ends up getting reported back as the git executable not existing, which is wrong.
Solution: create the directory chain for the namespace temp folder after saving settings.

**Comment by isc-tleavitt** [comment]
@CraigRegester this is a weird one... if you remove the quotes it re-adds, right? What's your IRIS version? And to confirm IRIS is running as cacheusr, right?

**Comment by CraigRegester** [comment]
Correct, just tried that (removing the quotes and saving) and yes, just added right back in. This is our I4H 2021.1.0 instance running on AIX 7.2. 

IRIS for UNIX (IBM AIX for System Power System-64) 2021.1 (Build 215U) Wed Jun 9 2021 09:55:44 EDT [Health:3.3.0]

Yes, running as cacheusr on the OS as this AIX server has been around that long!

**Comment by isc-tleavitt** [comment]
@CraigRegester can you also run:
zpm "list"

**Comment by CraigRegester** [comment]
For what it's worth, attempted to use the literal path (not the symbolic link) and that has the same issue:

![image](https://user-images.githubusercontent.com/65192819/141836716-06518529-4454-46d0-b6e6-662bb636adce.png)

For sake of completeness, also generated a new private key to ensure I hadn't nullified the previous one in the previous 2 months.

zpm list:
DEV:cacheusr>zpm "list"

git-source-control 1.1.2

**Comment by isc-tleavitt** [comment]
That kills off a bunch of theories... just sent an email re: connecting for a screen share.

**Comment by isc-tleavitt** [comment]
Note, we haven't tested on AIX specifically, but I'd be surprised if that was the culprit.

**Comment by isc-tleavitt** [comment]
Root cause: the namespace temp folder didn't exist. This ends up getting reported back as the git executable not existing, which is wrong.

Solution: create the directory chain for the namespace temp folder after saving settings.

**Comment by isc-tleavitt** [comment]
@isc-svelury I'd appreciate if you could knock this one out. ##class(%Library.File).CreateDirectoryChain(<directory chain>) will do what it sounds like. :)
