### ISSUE TITLE
Unable to commit using webgui

### ISSUE THREAD

**Issue by CraigRegester** [intersystems/git-source-control#72]
Hitting error pages when doing various things in the webui - switching branches, committing, doesn't matter as the errors are generally the same:

```
<ILLEGAL VALUE>zRunGitCommandWithInput+29^SourceControl.Git.Utils.1 : CSP Error
set returnCode = $zf(-100,"/STDOUT="_$select(outLog=$char(0):"$c(0)",1:$zu(144,1,outLog))_" /STDERR="_$select(errLog=$char(0):"$c(0)",1:$zu(144,1,errLog))_$Case(inFile, "":"", :" /STDIN="_inFile),command,newArgs...)
```

However, if I try a commit from the Source Control menu in the Management Portal (simple Production change), it works just fine.

```
exporting new version of FITLIB.Production.cls to /hfs/sys/git/FITLIB/cls/FITLIB/Production.cls
FITLIB.Production.CLS is the same as on-disk version or newer, skipping import

[dev 46edf1a] Test commit
1 file changed, 13 insertions(+)
create mode 100755 cls/FITLIB/Production.cls

/hfs/sys/git/FITLIB/cls/FITLIB/Production.cls removed from uncommitted list
```

Not clear to me which value is illegal. We are using an external (CSP) ISC Web Gateway but not sure if that's playing into it or not. I do see this in the stack dump that shows the call that was executing

ISCErrorInfo(1,"Class") = "SourceControl.Git.Utils"
• ISCErrorInfo(1,"Desc") = "A run-time error occurred while executing the page"
• ISCErrorInfo(1,"Error") = "<ILLEGAL VALUE>zRunGitCommandWithInput+29^SourceControl.Git.Utils.1"
• ISCErrorInfo(1,"ErrorNo") = 5002
• ISCErrorInfo(1,"Line") = " set returnCode = $zf(-100,"/STDOUT="_$select(outLog=$char(0):"$c(0)",1:$zu(144,1,outLog))_" /STDERR="_$select(errLog=$char(0):"$c(0)",1:$zu(144,1,errLog))_$Case(inFile, "":"", :" /STDIN="_inFile),command,newArgs...)"
• ISCErrorInfo(1,"Location") = "zRunGitCommandWithInput+29"
• ISCErrorInfo(1,"Namespace") = "FITLIB"
• ISCErrorInfo(1,"Routine") = "SourceControl.Git.Utils.1"
• ISCErrorInfo(1,"URL") = "/isc/studio/usertemplates/gitsourcecontrol/webuidriver.csp"
• ISCRequest(1) = "general information"
• ISCRequest(1,1) = "oref value: 1"
• ISCRequest(1,2) = "class name: %CSP.Request"
• ISCRequest(1,3) = "reference count: 5"
• ISCRequest(2,29) = "CgiEnvs("HTTP_HOST") = "iris-esb-dev.ourdomain.org""
• ISCRequest(2,3) = "Application = "/csp/sys/" <Set>"
• ISCRequest(2,30) = "CgiEnvs("HTTP_ORIGIN") = "https://iris-esb-dev.ourdomain.org""
• ISCRequest(2,31) = "CgiEnvs("HTTP_REFERER") = "https://iris-esb-dev.ourdomain.org/isc
--- cut out some junk here ---
• ISCRequest(2,31) = "CgiEnvs("HTTP_REFERER") = "https://iris-esb-dev.ourdomain.org/isc/studio/usertemplates/gitsourcecontrol/webuidriver.csp/FITLIB/FITLIB.Production.CLS?CSPSHARE=1&Project=&Document=iris-esb-dev.ourdomain.org%2FFITLIB%2FFITLIB.Production.CLS&Namespace=FITLIB&User=142990&CSPCHD=003001010000s2ZZVraT4BHeoWZ_W5atyuYe8wLl26KPEpGTf9""

**Comment by isc-tleavitt** [comment]
@isc-svelury I think we need to use $$$QUOTE on inFile as well.

**Comment by isc-tleavitt** [comment]
e.g., $Case(inFile, "":"", :" /STDIN="_$$$QUOTE(inFile))

**Comment by isc-tleavitt** [comment]
Some of the $zf(-100) behavior is platform-dependent; I think we just tested too gently on Linux.
@CraigRegester we'll get a new release out once this issue is fixed.

**Comment by isc-tleavitt** [comment]
@CraigRegester this should be fixed in v1.1.3 (available via zpm) if you want to give it a go

**Comment by CraigRegester** [comment]
Will give it a shot - go easy on me, today was the first time I've had a chance to use zpm as well :) Just zpm install again?

**Comment by isc-tleavitt** [comment]
@CraigRegester no need for reinstall, just should be able to say zpm "install git-source-control" and it'll pick up the new version

**Comment by CraigRegester** [comment]
It worked (or at least gave me no errors this time)! I'll keep poking, thank you both.

![image](https://user-images.githubusercontent.com/65192819/141855816-9d5fb5d6-da0b-42b3-9ead-3e89ef3e470a.png)
