### ISSUE TITLE
Documentation Note for AIX/*nix File Systems

### ISSUE THREAD

**Issue by CraigRegester** [intersystems/git-source-control#74]
This is a documentation/installation note I was reminded of this morning that I wanted to share so it is included in formalized documentation. If we start a Discussion section on this repo, happy to note things like this there.

Git repositories cannot be properly initialized on filesystems mounted with the cio mount option. No error will be thrown during the init but any attempt to use the repo will result in an error that there is no git repository present.

![image](https://user-images.githubusercontent.com/65192819/142013417-cc2b5b0b-54da-4a4a-91e6-1edec0950e1d.png)

```
git status
fatal: not a git repository (or any parent up to mount point /ucrfs)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

In my case, /ucrfs/sys was set with the cio mount option. cio mount option is necessary/preferred (per ISC Documentation) on journal filesystems (e.g., /ucrfs/jrn and /ucrfs/altjrn) but git will _not_ work with it. Fixing my mount options - our IRIS for Health instances have the /sys filesystem set without the cio mount option (we use it on the jrn/altjrn/db filesystem mount points however.)

**Comment by isc-tleavitt** [comment]
@CraigRegester thanks for bringing this up. I've started a Discussion section.

**Comment by isc-tleavitt** [comment]
Put this in the discussion section @ https://github.com/intersystems/git-source-control/discussions/86 ; closing the issue.

(I think this is a little obscure to live in the main documentation.)
