### ISSUE TITLE
Dots (.) are being escaped automatically on Schema exports (and likely other files)

### ISSUE THREAD

**Issue by CraigRegester** [intersystems/git-source-control#92]
This is happening both with git-source-control and the InterSystems Objectscript Extension (not using ISFS).

If I have a schema named FAEPIC_2.3.1.HL7 and Add (ISFS) or Export (non-ISFS), I get this:

InterSystems ObjectScript Extension Export:
`export "FAEPIC_2.3.1.HL7" as "c:\Users\142990\MyDev\ISC-HealthShare-UCR\FALIB\src\FAEPIC_2\3\1.hl7" - Success 
`

```
InterSystems git-source-control Export:
new file:   INTGBUS/hl7/FAEPIC_2/3/1.cls
```

Can we not escape the dots on schema exports? Creates a nasty folder structure.

**Comment by isc-tleavitt** [comment]
@isc-svelury if the type of the file is "Other" (e.g., in the old Studio view - that is, not a class/routine/include but instead a "user type" handled by some subclass of %Studio.AbstractDocument), we should preserve the name when exporting.

Note that if the package manager is in use all of this should just work; we're only interested in fixing the case where it isn't in use.

**Comment by isc-tleavitt** [comment]
Minor change in direction here: the dots-to-folders behavior can be suppressed via the "NoFolders" subscript under the file type. We should support this via the UI and set reasonable defaults for all user types. (BPL/DTL should continue to export as classes.)

**Comment by CraigRegester** [comment]
I think I get what you're saying - the filename itself can respect the NoFolders option but I can still folder my schemas together if I want right? E.g., extension HL7 goes into /hl7 folder so /hl7/2.3.1.hl7

**Comment by isc-tleavitt** [comment]
@CraigRegester that's correct.

**Comment by isc-tleavitt** [comment]
Relevant bit of code: https://github.com/intersystems/git-source-control/blob/main/cls/SourceControl/Git/Utils.cls#L1289

**Comment by CraigRegester** [comment]
Perfect, thanks @isc-tleavitt
